language: ruby
rvm:
  - 2.1.2

bundler_args: --without production

before_script: curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.9.0 SOLR_CONFS="./solr/conf/schema.xml ./solr/conf/solrconfig.xml" bash

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.default config/database.yml

