language: ruby
rvm:
  - 2.1.2

bundler_args: --without production

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake sunspot:solr:start RAILS_ENV=test
  - bundle exec rspec spec

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.default config/database.yml

