development:
  bucket: "123-development"
  access_key_id: 123...
  secret_access_key: 123...
test:
  bucket: "123-test"
  access_key_id: abc...
  secret_access_key: abc...
production:
  bucket: "123"
  access_key_id: 456...
  secret_access_key: 456...
