production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    min_memory: 512M
    max_memory: 1G
    #solr_jar: /path/to/start.jar
    #log_level: DEBUG
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    
