require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BdasController do

  # This should return the minimal set of attributes required to create a valid
  # Bda. As you add validations to Bda, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BdasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bdas as @bdas" do
      bda = Bda.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bdas).should eq([bda])
    end
  end

  describe "GET show" do
    it "assigns the requested bda as @bda" do
      bda = Bda.create! valid_attributes
      get :show, {:id => bda.to_param}, valid_session
      assigns(:bda).should eq(bda)
    end
  end

  describe "GET new" do
    it "assigns a new bda as @bda" do
      get :new, {}, valid_session
      assigns(:bda).should be_a_new(Bda)
    end
  end

  describe "GET edit" do
    it "assigns the requested bda as @bda" do
      bda = Bda.create! valid_attributes
      get :edit, {:id => bda.to_param}, valid_session
      assigns(:bda).should eq(bda)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bda" do
        expect {
          post :create, {:bda => valid_attributes}, valid_session
        }.to change(Bda, :count).by(1)
      end

      it "assigns a newly created bda as @bda" do
        post :create, {:bda => valid_attributes}, valid_session
        assigns(:bda).should be_a(Bda)
        assigns(:bda).should be_persisted
      end

      it "redirects to the created bda" do
        post :create, {:bda => valid_attributes}, valid_session
        response.should redirect_to(Bda.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bda as @bda" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bda.any_instance.stub(:save).and_return(false)
        post :create, {:bda => { "name" => "invalid value" }}, valid_session
        assigns(:bda).should be_a_new(Bda)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bda.any_instance.stub(:save).and_return(false)
        post :create, {:bda => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bda" do
        bda = Bda.create! valid_attributes
        # Assuming there are no other bdas in the database, this
        # specifies that the Bda created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bda.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => bda.to_param, :bda => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested bda as @bda" do
        bda = Bda.create! valid_attributes
        put :update, {:id => bda.to_param, :bda => valid_attributes}, valid_session
        assigns(:bda).should eq(bda)
      end

      it "redirects to the bda" do
        bda = Bda.create! valid_attributes
        put :update, {:id => bda.to_param, :bda => valid_attributes}, valid_session
        response.should redirect_to(bda)
      end
    end

    describe "with invalid params" do
      it "assigns the bda as @bda" do
        bda = Bda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bda.any_instance.stub(:save).and_return(false)
        put :update, {:id => bda.to_param, :bda => { "name" => "invalid value" }}, valid_session
        assigns(:bda).should eq(bda)
      end

      it "re-renders the 'edit' template" do
        bda = Bda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bda.any_instance.stub(:save).and_return(false)
        put :update, {:id => bda.to_param, :bda => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bda" do
      bda = Bda.create! valid_attributes
      expect {
        delete :destroy, {:id => bda.to_param}, valid_session
      }.to change(Bda, :count).by(-1)
    end

    it "redirects to the bdas list" do
      bda = Bda.create! valid_attributes
      delete :destroy, {:id => bda.to_param}, valid_session
      response.should redirect_to(bdas_url)
    end
  end

end
